apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  labels:
    nfs: jellyfin-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /media/mybook/k8sNFS/jellyfin-config/
    server: 192.168.1.142
